apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
      - name: doctor
        image: mohammadthaheer/doctor:latest
        ports:
        - containerPort: 3000  # Port your application listens on
