apiVersion: v1
kind: Service
metadata:
  name: doctor-service
spec:
  selector:
    app: doctor
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service externally (outside the cluster)
      targetPort: 3000  # Port your application listens on inside the pods
  type: LoadBalancer
